import { useState } from "react";
import databasePreview from "@/assets/database-preview.jpg";
import { ShopHeader } from "@/components/ShopHeader";
import { ProductTable, Product } from "@/components/ProductTable";
import { FileUploader } from "@/components/FileUploader";
import { Cart } from "@/components/Cart";
import { Dialog, DialogContent } from "@/components/ui/dialog";

interface CartItem extends Product {
  quantity: number;
}

// Sample data to showcase the shop
const sampleProducts: Product[] = [
  {
    id: "1",
    name: "E-commerce Customer Database",
    description: "Comprehensive customer data with purchase history, demographics, and behavior patterns",
    price: 199.99,
    category: "E-commerce",
    format: "CSV",
    records: 1250000,
    preview: databasePreview,
    tags: ["customers", "e-commerce", "analytics"],
    lastUpdated: "2024-01-15",
    source: "Global retailers",
    schema: "customer_id, email, first_name, last_name, age, gender, location, total_spent, last_purchase_date, preferred_categories"
  },
  {
    id: "2", 
    name: "Financial Markets Dataset",
    description: "Historical stock prices, trading volumes, and market indicators from 2010-2024",
    price: 599.99,
    category: "Finance",
    format: "JSON",
    records: 3400000,
    preview: databasePreview,
    tags: ["stocks", "finance", "trading"],
    lastUpdated: "2024-01-18",
    source: "Financial exchanges",
    schema: "symbol, company_name, date, open_price, high_price, low_price, close_price, volume, market_cap"
  },
  {
    id: "3",
    name: "Social Media Analytics",
    description: "Anonymized social media posts, engagement metrics, and sentiment analysis data",
    price: 149.99,
    category: "Social Media",
    format: "CSV",
    records: 890000,
    preview: databasePreview,
    tags: ["social-media", "analytics", "sentiment"],
    lastUpdated: "2024-01-12",
    source: "Social platforms",
    schema: "post_id, platform, user_id, content, engagement_score, sentiment, timestamp, hashtags"
  },
  {
    id: "4",
    name: "Real Estate Listings Database",
    description: "Property listings with prices, locations, features, and market trends",
    price: 249.99,
    category: "Real Estate",
    format: "XLSX",
    records: 750000,
    preview: databasePreview,
    tags: ["properties", "real-estate", "housing"],
    lastUpdated: "2024-01-16",
    source: "Property listings",
    schema: "property_id, address, city, state, zip_code, price, bedrooms, bathrooms, square_feet, property_type, year_built"
  },
  {
    id: "5",
    name: "Healthcare Research Data",
    description: "Clinical trial data, patient outcomes, and medical device performance metrics",
    price: 349.99,
    category: "Healthcare",
    format: "JSON",
    records: 2100000,
    preview: databasePreview,
    tags: ["healthcare", "medical", "research"],
    lastUpdated: "2024-01-10",
    source: "Medical institutions",
    schema: "patient_id, age_group, gender, diagnosis_codes, treatment_type, outcome, duration, insurance_type"
  },
  {
    id: "6",
    name: "Cryptocurrency Trading Data",
    description: "Bitcoin, Ethereum, and altcoin trading data with order books and price movements",
    price: 179.99,
    category: "Cryptocurrency",
    format: "CSV",
    records: 1890000,
    preview: databasePreview,
    tags: ["crypto", "trading", "blockchain"],
    lastUpdated: "2024-01-14",
    source: "Crypto exchanges",
    schema: "symbol, timestamp, open, high, low, close, volume, market_cap, circulating_supply"
  },
  {
    id: "7",
    name: "Australian NDIS database - ableaustralia.org.au",
    description: "Over 2000 Full information and documents on NDIS people and their families aswell as the organizations they belong too",
    price: 800,
    category: "Healthcare",
    format: "CSV",
    records: 2000,
    preview: databasePreview,
    tags: ["ndis", "healthcare", "australia"],
    lastUpdated: "2024-01-20",
    source: "ableaustralia.org.au",
    schema: "participant_id, name, family_info, organization, plan_details, support_needs, contact_info, documents"
  },
  {
    id: "8",
    name: "Sydney Business Registry - Australia",
    description: "Complete business registration data from Sydney metropolitan area",
    price: 299.99,
    category: "Business",
    format: "JSON",
    records: 458000,
    preview: databasePreview,
    tags: ["business", "australia", "sydney"],
    lastUpdated: "2024-01-19",
    source: "Australian Business Register",
    schema: "abn, business_name, industry, address, revenue_bracket, employee_count"
  },
  {
    id: "9",
    name: "Melbourne Property Sales Database",
    description: "Historical property sales data from Melbourne 2015-2024",
    price: 399.99,
    category: "Real Estate",
    format: "XLSX",
    records: 680000,
    preview: databasePreview,
    tags: ["property", "australia", "melbourne"],
    lastUpdated: "2024-01-18",
    source: "Victorian Land Registry",
    schema: "property_id, suburb, price, bedrooms, land_size, sale_date, property_type"
  },
  {
    id: "10",
    name: "US Consumer Credit Reports",
    description: "Anonymized consumer credit scores and financial behavior patterns",
    price: 449.99,
    category: "Finance",
    format: "CSV",
    records: 2100000,
    preview: databasePreview,
    tags: ["credit", "usa", "finance"],
    lastUpdated: "2024-01-17",
    source: "US Credit Bureaus",
    schema: "consumer_id, credit_score, debt_ratio, payment_history, credit_age"
  },
  {
    id: "11",
    name: "New York Restaurant Health Inspections",
    description: "Health inspection records for NYC restaurants 2020-2024",
    price: 149.99,
    category: "Government",
    format: "JSON",
    records: 95000,
    preview: databasePreview,
    tags: ["health", "usa", "nyc"],
    lastUpdated: "2024-01-16",
    source: "NYC Health Department",
    schema: "restaurant_id, name, address, inspection_date, violations, grade"
  },
  {
    id: "12",
    name: "California Vehicle Registration Database",
    description: "Vehicle registration data from California DMV",
    price: 549.99,
    category: "Transportation",
    format: "CSV",
    records: 15000000,
    preview: databasePreview,
    tags: ["vehicles", "usa", "california"],
    lastUpdated: "2024-01-15",
    source: "CA DMV",
    schema: "vin, make, model, year, owner_zip, registration_date"
  },
  {
    id: "13",
    name: "London Transport Usage Data",
    description: "Underground and bus journey patterns across London",
    price: 279.99,
    category: "Transportation",
    format: "JSON",
    records: 45000000,
    preview: databasePreview,
    tags: ["transport", "uk", "london"],
    lastUpdated: "2024-01-19",
    source: "Transport for London",
    schema: "journey_id, start_station, end_station, duration, fare, timestamp"
  },
  {
    id: "14",
    name: "UK Companies House Data",
    description: "Complete UK company registration and financial filing records",
    price: 499.99,
    category: "Business",
    format: "CSV",
    records: 4800000,
    preview: databasePreview,
    tags: ["business", "uk", "companies"],
    lastUpdated: "2024-01-18",
    source: "Companies House",
    schema: "company_number, name, sic_code, incorporation_date, accounts_date"
  },
  {
    id: "15",
    name: "Manchester Healthcare NHS Records",
    description: "Anonymized patient treatment and hospital admission data",
    price: 599.99,
    category: "Healthcare",
    format: "XLSX",
    records: 1200000,
    preview: databasePreview,
    tags: ["healthcare", "uk", "nhs"],
    lastUpdated: "2024-01-17",
    source: "NHS England",
    schema: "patient_id, age_group, admission_reason, treatment, length_of_stay"
  },
  {
    id: "16",
    name: "Toronto Real Estate MLS Listings",
    description: "Multiple Listing Service data from Greater Toronto Area",
    price: 399.99,
    category: "Real Estate",
    format: "JSON",
    records: 320000,
    preview: databasePreview,
    tags: ["property", "canada", "toronto"],
    lastUpdated: "2024-01-20",
    source: "Toronto Regional Real Estate Board",
    schema: "mls_id, address, price, bedrooms, bathrooms, square_feet, listing_date"
  },
  {
    id: "17",
    name: "Vancouver Business License Database",
    description: "Active business licenses in Vancouver metropolitan area",
    price: 249.99,
    category: "Business",
    format: "CSV",
    records: 78000,
    preview: databasePreview,
    tags: ["business", "canada", "vancouver"],
    lastUpdated: "2024-01-19",
    source: "City of Vancouver",
    schema: "license_number, business_name, address, business_type, issue_date"
  },
  {
    id: "18",
    name: "Canadian Healthcare Claims Data",
    description: "Provincial healthcare claims and prescription data",
    price: 699.99,
    category: "Healthcare",
    format: "XLSX",
    records: 28000000,
    preview: databasePreview,
    tags: ["healthcare", "canada", "insurance"],
    lastUpdated: "2024-01-18",
    source: "Canadian Health Authorities",
    schema: "claim_id, province, service_type, cost, date, provider_id"
  },
  {
    id: "19",
    name: "Auckland Property Valuations - NZ",
    description: "Government property valuations for Auckland region",
    price: 349.99,
    category: "Real Estate",
    format: "JSON",
    records: 480000,
    preview: databasePreview,
    tags: ["property", "new-zealand", "auckland"],
    lastUpdated: "2024-01-17",
    source: "Auckland Council",
    schema: "property_id, address, valuation, land_area, improvement_value, rates"
  },
  {
    id: "20",
    name: "Wellington Business Directory - NZ",
    description: "Comprehensive business directory for Wellington region",
    price: 199.99,
    category: "Business",
    format: "CSV",
    records: 45000,
    preview: databasePreview,
    tags: ["business", "new-zealand", "wellington"],
    lastUpdated: "2024-01-16",
    source: "NZ Business Register",
    schema: "nzbn, business_name, industry, address, phone, website"
  },
  {
    id: "21",
    name: "Christchurch Insurance Claims Data",
    description: "Post-earthquake insurance claims and settlements",
    price: 449.99,
    category: "Insurance",
    format: "XLSX",
    records: 120000,
    preview: databasePreview,
    tags: ["insurance", "new-zealand", "christchurch"],
    lastUpdated: "2024-01-15",
    source: "NZ Insurance Council",
    schema: "claim_id, property_address, claim_amount, settlement_amount, claim_date"
  },
  {
    id: "22",
    name: "Hong Kong Stock Exchange Data",
    description: "Complete HSI constituent trading data 2020-2024",
    price: 699.99,
    category: "Finance",
    format: "JSON",
    records: 8900000,
    preview: databasePreview,
    tags: ["stocks", "hong-kong", "hkex"],
    lastUpdated: "2024-01-20",
    source: "Hong Kong Stock Exchange",
    schema: "ticker, company_name, date, open, high, low, close, volume, market_cap"
  },
  {
    id: "23",
    name: "HK Commercial Property Transactions",
    description: "Commercial real estate transaction records",
    price: 549.99,
    category: "Real Estate",
    format: "CSV",
    records: 180000,
    preview: databasePreview,
    tags: ["property", "hong-kong", "commercial"],
    lastUpdated: "2024-01-19",
    source: "Land Registry HK",
    schema: "transaction_id, property_address, price_hkd, area_sqft, transaction_date"
  },
  {
    id: "24",
    name: "Hong Kong Company Registry",
    description: "Registered company data with directors and shareholders",
    price: 399.99,
    category: "Business",
    format: "XLSX",
    records: 1300000,
    preview: databasePreview,
    tags: ["business", "hong-kong", "companies"],
    lastUpdated: "2024-01-18",
    source: "Companies Registry HK",
    schema: "company_number, name, incorporation_date, directors, shareholders"
  },
  {
    id: "25",
    name: "São Paulo Consumer Database - Brazil",
    description: "Consumer behavior and purchasing patterns from São Paulo",
    price: 329.99,
    category: "E-commerce",
    format: "JSON",
    records: 2800000,
    preview: databasePreview,
    tags: ["consumers", "brazil", "sao-paulo"],
    lastUpdated: "2024-01-17",
    source: "Brazilian Retailers",
    schema: "consumer_id, age, income_bracket, purchase_category, spending_habits"
  },
  {
    id: "26",
    name: "Rio de Janeiro Real Estate Listings",
    description: "Property listings for Rio metropolitan area",
    price: 279.99,
    category: "Real Estate",
    format: "CSV",
    records: 420000,
    preview: databasePreview,
    tags: ["property", "brazil", "rio"],
    lastUpdated: "2024-01-16",
    source: "Brazilian Property Sites",
    schema: "listing_id, neighborhood, price_brl, bedrooms, area_sqm, amenities"
  },
  {
    id: "27",
    name: "Brazilian Agricultural Production Data",
    description: "Crop yields, livestock, and farming statistics by region",
    price: 449.99,
    category: "Agriculture",
    format: "XLSX",
    records: 650000,
    preview: databasePreview,
    tags: ["agriculture", "brazil", "farming"],
    lastUpdated: "2024-01-15",
    source: "Brazilian Agriculture Ministry",
    schema: "farm_id, region, crop_type, yield, area_hectares, harvest_date"
  },
  {
    id: "28",
    name: "Buenos Aires Business Registry - Argentina",
    description: "Complete business registration data from Buenos Aires",
    price: 249.99,
    category: "Business",
    format: "JSON",
    records: 380000,
    preview: databasePreview,
    tags: ["business", "argentina", "buenos-aires"],
    lastUpdated: "2024-01-20",
    source: "AFIP Argentina",
    schema: "cuit, business_name, industry, address, registration_date"
  },
  {
    id: "29",
    name: "Argentine Real Estate Transactions",
    description: "Property sale and rental data from major Argentine cities",
    price: 349.99,
    category: "Real Estate",
    format: "CSV",
    records: 560000,
    preview: databasePreview,
    tags: ["property", "argentina", "real-estate"],
    lastUpdated: "2024-01-19",
    source: "Argentine Property Registry",
    schema: "property_id, city, transaction_type, price_ars, area_sqm, date"
  },
  {
    id: "30",
    name: "Argentina Financial Market Data",
    description: "MERVAL index stocks and bond trading data",
    price: 399.99,
    category: "Finance",
    format: "XLSX",
    records: 1200000,
    preview: databasePreview,
    tags: ["finance", "argentina", "stocks"],
    lastUpdated: "2024-01-18",
    source: "Buenos Aires Stock Exchange",
    schema: "ticker, date, open, high, low, close, volume, currency"
  },
  {
    id: "31",
    name: "Berlin Startup Database - Germany",
    description: "Comprehensive data on Berlin tech startups and funding",
    price: 449.99,
    category: "Business",
    format: "JSON",
    records: 8500,
    preview: databasePreview,
    tags: ["startups", "germany", "berlin"],
    lastUpdated: "2024-01-17",
    source: "German Startup Association",
    schema: "company_name, founding_date, industry, funding_rounds, total_funding"
  },
  {
    id: "32",
    name: "Munich Automotive Industry Data",
    description: "Vehicle production, sales, and supplier network data",
    price: 599.99,
    category: "Automotive",
    format: "CSV",
    records: 980000,
    preview: databasePreview,
    tags: ["automotive", "germany", "munich"],
    lastUpdated: "2024-01-16",
    source: "German Auto Association",
    schema: "manufacturer, model, production_volume, sales, export_data"
  },
  {
    id: "33",
    name: "German Real Estate Market Analysis",
    description: "Property prices and rental data from major German cities",
    price: 499.99,
    category: "Real Estate",
    format: "XLSX",
    records: 1400000,
    preview: databasePreview,
    tags: ["property", "germany", "real-estate"],
    lastUpdated: "2024-01-15",
    source: "German Property Association",
    schema: "city, property_type, price_eur, size_sqm, year_built, energy_rating"
  },
  {
    id: "34",
    name: "Paris Restaurant Database - France",
    description: "Complete restaurant listings with reviews and ratings",
    price: 199.99,
    category: "Hospitality",
    format: "JSON",
    records: 28000,
    preview: databasePreview,
    tags: ["restaurants", "france", "paris"],
    lastUpdated: "2024-01-20",
    source: "French Tourism Board",
    schema: "restaurant_id, name, address, cuisine_type, rating, price_range"
  },
  {
    id: "35",
    name: "French Wine Production Database",
    description: "Vineyard data, production volumes, and quality ratings",
    price: 549.99,
    category: "Agriculture",
    format: "CSV",
    records: 450000,
    preview: databasePreview,
    tags: ["wine", "france", "agriculture"],
    lastUpdated: "2024-01-19",
    source: "French Wine Authority",
    schema: "vineyard_name, region, appellation, production_volume, vintage_year"
  },
  {
    id: "36",
    name: "Lyon Business Directory - France",
    description: "Business registration and financial data from Lyon region",
    price: 349.99,
    category: "Business",
    format: "XLSX",
    records: 180000,
    preview: databasePreview,
    tags: ["business", "france", "lyon"],
    lastUpdated: "2024-01-18",
    source: "French Business Registry",
    schema: "siret, company_name, activity_code, employees, revenue, address"
  },
  {
    id: "37",
    name: "Perth Mining Industry Database - Australia",
    description: "Mining operations, production data, and resource estimates",
    price: 699.99,
    category: "Mining",
    format: "JSON",
    records: 12000,
    preview: databasePreview,
    tags: ["mining", "australia", "perth"],
    lastUpdated: "2024-01-17",
    source: "Australian Mining Association",
    schema: "mine_id, location, resource_type, production_volume, reserves"
  },
  {
    id: "38",
    name: "Brisbane Education Statistics",
    description: "School performance data, enrollment, and demographics",
    price: 299.99,
    category: "Education",
    format: "CSV",
    records: 85000,
    preview: databasePreview,
    tags: ["education", "australia", "brisbane"],
    lastUpdated: "2024-01-16",
    source: "Queensland Education Dept",
    schema: "school_id, name, type, enrollment, test_scores, demographics"
  },
  {
    id: "39",
    name: "Adelaide Healthcare Provider Database",
    description: "Medical practitioners, clinics, and healthcare facilities",
    price: 349.99,
    category: "Healthcare",
    format: "XLSX",
    records: 23000,
    preview: databasePreview,
    tags: ["healthcare", "australia", "adelaide"],
    lastUpdated: "2024-01-15",
    source: "Australian Health Practitioner Regulation",
    schema: "provider_id, name, specialty, location, accreditation"
  },
  {
    id: "40",
    name: "Texas Oil & Gas Production Data",
    description: "Well production, reserves, and operator information",
    price: 799.99,
    category: "Energy",
    format: "JSON",
    records: 450000,
    preview: databasePreview,
    tags: ["energy", "usa", "texas"],
    lastUpdated: "2024-01-20",
    source: "Texas Railroad Commission",
    schema: "well_id, operator, production_volume, location, permit_date"
  },
  {
    id: "41",
    name: "Chicago Crime Statistics Database",
    description: "Detailed crime incident reports from Chicago PD 2015-2024",
    price: 249.99,
    category: "Government",
    format: "CSV",
    records: 1800000,
    preview: databasePreview,
    tags: ["crime", "usa", "chicago"],
    lastUpdated: "2024-01-19",
    source: "Chicago Police Department",
    schema: "incident_id, date, crime_type, location, arrest_made, district"
  },
  {
    id: "42",
    name: "Florida Tourism Data",
    description: "Visitor statistics, hotel occupancy, and tourism revenue",
    price: 399.99,
    category: "Tourism",
    format: "XLSX",
    records: 680000,
    preview: databasePreview,
    tags: ["tourism", "usa", "florida"],
    lastUpdated: "2024-01-18",
    source: "Visit Florida",
    schema: "location, visitor_count, origin, spending, accommodation_type"
  },
  {
    id: "43",
    name: "Birmingham Property Database - UK",
    description: "Residential and commercial property records",
    price: 329.99,
    category: "Real Estate",
    format: "JSON",
    records: 420000,
    preview: databasePreview,
    tags: ["property", "uk", "birmingham"],
    lastUpdated: "2024-01-17",
    source: "UK Land Registry",
    schema: "property_id, address, price, property_type, transaction_date"
  },
  {
    id: "44",
    name: "Glasgow Healthcare Records",
    description: "Scottish NHS patient data and treatment outcomes",
    price: 549.99,
    category: "Healthcare",
    format: "CSV",
    records: 890000,
    preview: databasePreview,
    tags: ["healthcare", "uk", "scotland"],
    lastUpdated: "2024-01-16",
    source: "NHS Scotland",
    schema: "patient_id, health_board, diagnosis, treatment, outcome"
  },
  {
    id: "45",
    name: "Edinburgh Financial Services Data",
    description: "Financial institutions, services, and employment data",
    price: 449.99,
    category: "Finance",
    format: "XLSX",
    records: 15000,
    preview: databasePreview,
    tags: ["finance", "uk", "edinburgh"],
    lastUpdated: "2024-01-15",
    source: "Scottish Financial Enterprise",
    schema: "company_name, service_type, employees, assets, location"
  },
  {
    id: "46",
    name: "Montreal Bilingual Business Directory",
    description: "Quebec business listings with language service info",
    price: 279.99,
    category: "Business",
    format: "JSON",
    records: 95000,
    preview: databasePreview,
    tags: ["business", "canada", "montreal"],
    lastUpdated: "2024-01-20",
    source: "Quebec Business Registry",
    schema: "neq, business_name, industry, languages, address, employees"
  },
  {
    id: "47",
    name: "Calgary Energy Sector Database",
    description: "Oil and gas companies, employment, and project data",
    price: 649.99,
    category: "Energy",
    format: "CSV",
    records: 28000,
    preview: databasePreview,
    tags: ["energy", "canada", "calgary"],
    lastUpdated: "2024-01-19",
    source: "Alberta Energy Regulator",
    schema: "company_name, projects, employees, production, reserves"
  },
  {
    id: "48",
    name: "Ottawa Government Contracts Database",
    description: "Federal government procurement and contract awards",
    price: 499.99,
    category: "Government",
    format: "XLSX",
    records: 120000,
    preview: databasePreview,
    tags: ["government", "canada", "ottawa"],
    lastUpdated: "2024-01-18",
    source: "Public Services Canada",
    schema: "contract_id, vendor, amount, department, award_date, description"
  },
  {
    id: "49",
    name: "Queenstown Tourism Database - NZ",
    description: "Visitor data, activities, and accommodation bookings",
    price: 329.99,
    category: "Tourism",
    format: "JSON",
    records: 180000,
    preview: databasePreview,
    tags: ["tourism", "new-zealand", "queenstown"],
    lastUpdated: "2024-01-17",
    source: "Tourism New Zealand",
    schema: "visitor_id, origin_country, activities, spending, stay_duration"
  },
  {
    id: "50",
    name: "Dunedin Education Database - NZ",
    description: "University and school enrollment, research data",
    price: 249.99,
    category: "Education",
    format: "CSV",
    records: 45000,
    preview: databasePreview,
    tags: ["education", "new-zealand", "dunedin"],
    lastUpdated: "2024-01-16",
    source: "NZ Education Ministry",
    schema: "institution_name, enrollment, programs, research_funding"
  },
  {
    id: "51",
    name: "Hamilton Agriculture Data - NZ",
    description: "Farming operations, livestock, and dairy production",
    price: 399.99,
    category: "Agriculture",
    format: "XLSX",
    records: 12000,
    preview: databasePreview,
    tags: ["agriculture", "new-zealand", "hamilton"],
    lastUpdated: "2024-01-15",
    source: "NZ Agriculture Ministry",
    schema: "farm_id, farm_type, livestock_count, production_volume, area"
  },
  {
    id: "52",
    name: "Kowloon Retail Sales Database - HK",
    description: "Retail store sales data and consumer patterns",
    price: 449.99,
    category: "Retail",
    format: "JSON",
    records: 2400000,
    preview: databasePreview,
    tags: ["retail", "hong-kong", "kowloon"],
    lastUpdated: "2024-01-20",
    source: "Hong Kong Retail Association",
    schema: "store_id, category, sales, customer_count, location"
  },
  {
    id: "53",
    name: "Hong Kong Immigration Statistics",
    description: "Immigration and visa application data",
    price: 349.99,
    category: "Government",
    format: "CSV",
    records: 3800000,
    preview: databasePreview,
    tags: ["immigration", "hong-kong", "government"],
    lastUpdated: "2024-01-19",
    source: "HK Immigration Department",
    schema: "application_id, visa_type, nationality, approval_status, date"
  },
  {
    id: "54",
    name: "Macau Casino Gaming Data - HK Region",
    description: "Gaming revenue, visitor statistics, and market data",
    price: 699.99,
    category: "Gaming",
    format: "XLSX",
    records: 580000,
    preview: databasePreview,
    tags: ["gaming", "hong-kong", "macau"],
    lastUpdated: "2024-01-18",
    source: "Macau Gaming Authority",
    schema: "casino_name, revenue, visitor_count, gaming_type, date"
  },
  {
    id: "55",
    name: "Brasília Government Procurement - Brazil",
    description: "Federal government contracts and bidding data",
    price: 549.99,
    category: "Government",
    format: "JSON",
    records: 280000,
    preview: databasePreview,
    tags: ["government", "brazil", "brasilia"],
    lastUpdated: "2024-01-17",
    source: "Brazilian Federal Government",
    schema: "contract_id, vendor, amount_brl, department, date, status"
  },
  {
    id: "56",
    name: "Salvador Tourism Database - Brazil",
    description: "Tourist arrivals, accommodation, and attraction data",
    price: 299.99,
    category: "Tourism",
    format: "CSV",
    records: 420000,
    preview: databasePreview,
    tags: ["tourism", "brazil", "salvador"],
    lastUpdated: "2024-01-16",
    source: "Bahia Tourism Board",
    schema: "visitor_id, origin, stay_duration, spending, attractions_visited"
  },
  {
    id: "57",
    name: "Brazilian E-commerce Database",
    description: "Online retail transactions and consumer behavior",
    price: 449.99,
    category: "E-commerce",
    format: "XLSX",
    records: 8900000,
    preview: databasePreview,
    tags: ["e-commerce", "brazil", "retail"],
    lastUpdated: "2024-01-15",
    source: "Brazilian E-commerce Association",
    schema: "order_id, customer_id, product_category, value_brl, payment_method"
  },
  {
    id: "58",
    name: "Córdoba University Database - Argentina",
    description: "Student enrollment, faculty, and research data",
    price: 249.99,
    category: "Education",
    format: "JSON",
    records: 95000,
    preview: databasePreview,
    tags: ["education", "argentina", "cordoba"],
    lastUpdated: "2024-01-20",
    source: "Argentine Education Ministry",
    schema: "student_id, program, enrollment_date, performance, faculty"
  },
  {
    id: "59",
    name: "Mendoza Wine Export Data - Argentina",
    description: "Wine production and international export statistics",
    price: 399.99,
    category: "Agriculture",
    format: "CSV",
    records: 45000,
    preview: databasePreview,
    tags: ["wine", "argentina", "mendoza"],
    lastUpdated: "2024-01-19",
    source: "Argentine Wine Institute",
    schema: "winery_name, production_volume, export_country, value_usd"
  },
  {
    id: "60",
    name: "Rosario Industrial Database - Argentina",
    description: "Manufacturing and industrial production data",
    price: 449.99,
    category: "Manufacturing",
    format: "XLSX",
    records: 18000,
    preview: databasePreview,
    tags: ["manufacturing", "argentina", "rosario"],
    lastUpdated: "2024-01-18",
    source: "Argentine Industrial Association",
    schema: "company_name, industry, production_volume, employees, exports"
  },
  {
    id: "61",
    name: "Hamburg Port Logistics Database - Germany",
    description: "Shipping container data, cargo volumes, and routes",
    price: 599.99,
    category: "Logistics",
    format: "JSON",
    records: 1200000,
    preview: databasePreview,
    tags: ["logistics", "germany", "hamburg"],
    lastUpdated: "2024-01-17",
    source: "Hamburg Port Authority",
    schema: "container_id, origin, destination, cargo_type, weight, date"
  },
  {
    id: "62",
    name: "Frankfurt Banking Database - Germany",
    description: "Financial institutions, transactions, and market data",
    price: 749.99,
    category: "Finance",
    format: "CSV",
    records: 4500000,
    preview: databasePreview,
    tags: ["banking", "germany", "frankfurt"],
    lastUpdated: "2024-01-16",
    source: "Deutsche Bundesbank",
    schema: "institution_id, transaction_type, amount_eur, date, counterparty"
  },
  {
    id: "63",
    name: "Cologne Media Industry Database - Germany",
    description: "Broadcasting, publishing, and media company data",
    price: 349.99,
    category: "Media",
    format: "XLSX",
    records: 8500,
    preview: databasePreview,
    tags: ["media", "germany", "cologne"],
    lastUpdated: "2024-01-15",
    source: "German Media Association",
    schema: "company_name, media_type, revenue, employees, market_share"
  },
  {
    id: "64",
    name: "Marseille Port Trade Database - France",
    description: "Mediterranean shipping and trade statistics",
    price: 499.99,
    category: "Logistics",
    format: "JSON",
    records: 890000,
    preview: databasePreview,
    tags: ["logistics", "france", "marseille"],
    lastUpdated: "2024-01-20",
    source: "Port of Marseille Authority",
    schema: "shipment_id, cargo_type, origin, destination, volume, value_eur"
  },
  {
    id: "65",
    name: "Nice Tourism Database - France",
    description: "French Riviera visitor data and hospitality statistics",
    price: 399.99,
    category: "Tourism",
    format: "CSV",
    records: 620000,
    preview: databasePreview,
    tags: ["tourism", "france", "nice"],
    lastUpdated: "2024-01-19",
    source: "French Tourism Board",
    schema: "visitor_id, nationality, accommodation, spending, activities"
  },
  {
    id: "66",
    name: "Toulouse Aerospace Database - France",
    description: "Aviation industry suppliers, production, and employment",
    price: 649.99,
    category: "Aerospace",
    format: "XLSX",
    records: 12000,
    preview: databasePreview,
    tags: ["aerospace", "france", "toulouse"],
    lastUpdated: "2024-01-18",
    source: "French Aerospace Association",
    schema: "company_name, products, employees, contracts, certifications"
  },
  {
    id: "67",
    name: "Gold Coast Tourism Data - Australia",
    description: "Theme park visitors, beach activity, accommodation",
    price: 349.99,
    category: "Tourism",
    format: "JSON",
    records: 480000,
    preview: databasePreview,
    tags: ["tourism", "australia", "gold-coast"],
    lastUpdated: "2024-01-17",
    source: "Tourism Gold Coast",
    schema: "visitor_id, attractions, accommodation_type, spending, duration"
  },
  {
    id: "68",
    name: "Canberra Government Employment Database",
    description: "Federal public service employment and salary data",
    price: 449.99,
    category: "Government",
    format: "CSV",
    records: 180000,
    preview: databasePreview,
    tags: ["government", "australia", "canberra"],
    lastUpdated: "2024-01-16",
    source: "Australian Public Service Commission",
    schema: "employee_id, department, position, salary_band, location"
  },
  {
    id: "69",
    name: "Hobart Marine Industry Database - Australia",
    description: "Fishing, aquaculture, and marine research data",
    price: 299.99,
    category: "Maritime",
    format: "XLSX",
    records: 8500,
    preview: databasePreview,
    tags: ["maritime", "australia", "hobart"],
    lastUpdated: "2024-01-15",
    source: "Tasmanian Marine Industry",
    schema: "operator_name, activity_type, catch_volume, species, location"
  },
  {
    id: "70",
    name: "Boston Healthcare Network Database",
    description: "Hospital networks, patient volumes, research facilities",
    price: 599.99,
    category: "Healthcare",
    format: "JSON",
    records: 2400000,
    preview: databasePreview,
    tags: ["healthcare", "usa", "boston"],
    lastUpdated: "2024-01-20",
    source: "Massachusetts Health Dept",
    schema: "facility_id, type, bed_count, patient_volume, specialties"
  },
  {
    id: "71",
    name: "Seattle Tech Industry Database",
    description: "Software companies, startups, employment, and funding",
    price: 549.99,
    category: "Technology",
    format: "CSV",
    records: 15000,
    preview: databasePreview,
    tags: ["tech", "usa", "seattle"],
    lastUpdated: "2024-01-19",
    source: "Seattle Tech Alliance",
    schema: "company_name, employees, funding, products, founding_date"
  },
  {
    id: "72",
    name: "Las Vegas Casino Operations Data",
    description: "Gaming revenue, hotel occupancy, visitor statistics",
    price: 699.99,
    category: "Gaming",
    format: "XLSX",
    records: 1800000,
    preview: databasePreview,
    tags: ["gaming", "usa", "las-vegas"],
    lastUpdated: "2024-01-18",
    source: "Nevada Gaming Commission",
    schema: "property_name, gaming_revenue, occupancy_rate, visitor_count"
  },
  {
    id: "73",
    name: "Bristol Aerospace Database - UK",
    description: "Aviation and aerospace manufacturing and R&D data",
    price: 499.99,
    category: "Aerospace",
    format: "JSON",
    records: 8500,
    preview: databasePreview,
    tags: ["aerospace", "uk", "bristol"],
    lastUpdated: "2024-01-17",
    source: "UK Aerospace Association",
    schema: "company_name, products, employees, contracts, research_areas"
  },
  {
    id: "74",
    name: "Leeds Financial Services Database",
    description: "Banking, insurance, and financial services employment",
    price: 399.99,
    category: "Finance",
    format: "CSV",
    records: 42000,
    preview: databasePreview,
    tags: ["finance", "uk", "leeds"],
    lastUpdated: "2024-01-16",
    source: "Financial Services Leeds",
    schema: "company_name, service_type, employees, revenue, location"
  },
  {
    id: "75",
    name: "Cardiff Property Development Database",
    description: "Construction projects, property development, planning",
    price: 349.99,
    category: "Real Estate",
    format: "XLSX",
    records: 28000,
    preview: databasePreview,
    tags: ["property", "uk", "cardiff"],
    lastUpdated: "2024-01-15",
    source: "Welsh Property Development",
    schema: "project_id, developer, location, units, value, completion_date"
  },
  {
    id: "76",
    name: "Quebec City Tourism Database - Canada",
    description: "Historic sites visitors, hotels, cultural events",
    price: 299.99,
    category: "Tourism",
    format: "JSON",
    records: 380000,
    preview: databasePreview,
    tags: ["tourism", "canada", "quebec"],
    lastUpdated: "2024-01-20",
    source: "Quebec Tourism",
    schema: "visitor_id, attractions, accommodation, spending, season"
  },
  {
    id: "77",
    name: "Winnipeg Agriculture Database - Canada",
    description: "Grain production, livestock, farming operations",
    price: 399.99,
    category: "Agriculture",
    format: "CSV",
    records: 45000,
    preview: databasePreview,
    tags: ["agriculture", "canada", "winnipeg"],
    lastUpdated: "2024-01-19",
    source: "Manitoba Agriculture",
    schema: "farm_id, crop_type, yield, livestock_count, farm_size"
  },
  {
    id: "78",
    name: "Halifax Maritime Database - Canada",
    description: "Shipping, fishing industry, port operations",
    price: 449.99,
    category: "Maritime",
    format: "XLSX",
    records: 120000,
    preview: databasePreview,
    tags: ["maritime", "canada", "halifax"],
    lastUpdated: "2024-01-18",
    source: "Nova Scotia Maritime Authority",
    schema: "vessel_id, cargo_type, route, tonnage, port_calls"
  },
  {
    id: "79",
    name: "Tauranga Export Database - NZ",
    description: "Port export data, kiwifruit, forestry products",
    price: 349.99,
    category: "Logistics",
    format: "JSON",
    records: 280000,
    preview: databasePreview,
    tags: ["logistics", "new-zealand", "tauranga"],
    lastUpdated: "2024-01-17",
    source: "Port of Tauranga",
    schema: "shipment_id, product_type, destination, volume, value_nzd"
  },
  {
    id: "80",
    name: "Rotorua Tourism Database - NZ",
    description: "Geothermal attractions, Maori culture, visitor data",
    price: 279.99,
    category: "Tourism",
    format: "CSV",
    records: 420000,
    preview: databasePreview,
    tags: ["tourism", "new-zealand", "rotorua"],
    lastUpdated: "2024-01-16",
    source: "Tourism Rotorua",
    schema: "visitor_id, activities, spending, origin, satisfaction"
  },
  {
    id: "81",
    name: "Nelson Wine & Agriculture Data - NZ",
    description: "Vineyards, horticulture, wine production",
    price: 329.99,
    category: "Agriculture",
    format: "XLSX",
    records: 8500,
    preview: databasePreview,
    tags: ["agriculture", "new-zealand", "nelson"],
    lastUpdated: "2024-01-15",
    source: "Nelson Wine Association",
    schema: "vineyard_name, production_volume, varieties, export_markets"
  },
  {
    id: "82",
    name: "Shenzhen Tech Manufacturing Database - HK",
    description: "Electronics manufacturing, supply chain, exports",
    price: 649.99,
    category: "Manufacturing",
    format: "JSON",
    records: 450000,
    preview: databasePreview,
    tags: ["manufacturing", "hong-kong", "shenzhen"],
    lastUpdated: "2024-01-20",
    source: "Shenzhen Industrial Association",
    schema: "company_name, products, production_volume, employees, exports"
  },
  {
    id: "83",
    name: "Hong Kong Fintech Database",
    description: "Financial technology startups, funding, products",
    price: 549.99,
    category: "Technology",
    format: "CSV",
    records: 2800,
    preview: databasePreview,
    tags: ["fintech", "hong-kong", "technology"],
    lastUpdated: "2024-01-19",
    source: "Hong Kong Fintech Association",
    schema: "company_name, product_type, funding, employees, launch_date"
  },
  {
    id: "84",
    name: "New Territories Property Database - HK",
    description: "Residential development, land use, property prices",
    price: 499.99,
    category: "Real Estate",
    format: "XLSX",
    records: 380000,
    preview: databasePreview,
    tags: ["property", "hong-kong", "new-territories"],
    lastUpdated: "2024-01-18",
    source: "HK Land Registry",
    schema: "property_id, location, price_hkd, type, size_sqft, age"
  },
  {
    id: "85",
    name: "Recife Port Operations - Brazil",
    description: "Container shipping, cargo volumes, trade routes",
    price: 399.99,
    category: "Logistics",
    format: "JSON",
    records: 480000,
    preview: databasePreview,
    tags: ["logistics", "brazil", "recife"],
    lastUpdated: "2024-01-17",
    source: "Port of Recife",
    schema: "shipment_id, cargo_type, origin, destination, weight"
  },
  {
    id: "86",
    name: "Curitiba Urban Planning Database - Brazil",
    description: "City infrastructure, public transport, urban development",
    price: 349.99,
    category: "Government",
    format: "CSV",
    records: 120000,
    preview: databasePreview,
    tags: ["government", "brazil", "curitiba"],
    lastUpdated: "2024-01-16",
    source: "Curitiba Municipality",
    schema: "project_id, type, budget_brl, completion_date, location"
  },
  {
    id: "87",
    name: "Manaus Free Trade Zone Database - Brazil",
    description: "Industrial park companies, production, employment",
    price: 549.99,
    category: "Manufacturing",
    format: "XLSX",
    records: 12000,
    preview: databasePreview,
    tags: ["manufacturing", "brazil", "manaus"],
    lastUpdated: "2024-01-15",
    source: "SUFRAMA Brazil",
    schema: "company_name, industry, production_volume, employees, exports"
  },
  {
    id: "88",
    name: "Mar del Plata Tourism Database - Argentina",
    description: "Beach resort visitors, accommodation, seasonal data",
    price: 279.99,
    category: "Tourism",
    format: "JSON",
    records: 680000,
    preview: databasePreview,
    tags: ["tourism", "argentina", "mar-del-plata"],
    lastUpdated: "2024-01-20",
    source: "Mar del Plata Tourism Board",
    schema: "visitor_id, origin, stay_duration, spending, season"
  },
  {
    id: "89",
    name: "Bariloche Tourism Database - Argentina",
    description: "Ski resort data, hotel bookings, adventure tourism",
    price: 329.99,
    category: "Tourism",
    format: "CSV",
    records: 420000,
    preview: databasePreview,
    tags: ["tourism", "argentina", "bariloche"],
    lastUpdated: "2024-01-19",
    source: "Bariloche Tourism",
    schema: "visitor_id, activities, accommodation, spending, season"
  },
  {
    id: "90",
    name: "La Plata University Database - Argentina",
    description: "Student enrollment, research projects, faculty data",
    price: 249.99,
    category: "Education",
    format: "XLSX",
    records: 110000,
    preview: databasePreview,
    tags: ["education", "argentina", "la-plata"],
    lastUpdated: "2024-01-18",
    source: "National University of La Plata",
    schema: "student_id, program, enrollment_date, faculty, performance"
  },
  {
    id: "91",
    name: "Dresden Semiconductor Database - Germany",
    description: "Chip manufacturing, research facilities, employment",
    price: 699.99,
    category: "Technology",
    format: "JSON",
    records: 15000,
    preview: databasePreview,
    tags: ["technology", "germany", "dresden"],
    lastUpdated: "2024-01-17",
    source: "Silicon Saxony",
    schema: "company_name, products, production_volume, employees, r&d"
  },
  {
    id: "92",
    name: "Stuttgart Automotive Database - Germany",
    description: "Vehicle manufacturing, suppliers, innovation data",
    price: 649.99,
    category: "Automotive",
    format: "CSV",
    records: 280000,
    preview: databasePreview,
    tags: ["automotive", "germany", "stuttgart"],
    lastUpdated: "2024-01-16",
    source: "Baden-Württemberg Automotive",
    schema: "company_name, product_type, production, employees, exports"
  },
  {
    id: "93",
    name: "Düsseldorf Fashion Industry Database - Germany",
    description: "Fashion companies, retail, trade shows, employment",
    price: 399.99,
    category: "Retail",
    format: "XLSX",
    records: 8500,
    preview: databasePreview,
    tags: ["fashion", "germany", "dusseldorf"],
    lastUpdated: "2024-01-15",
    source: "German Fashion Association",
    schema: "company_name, brand, revenue, employees, market_segment"
  },
  {
    id: "94",
    name: "Strasbourg European Parliament Database",
    description: "Parliamentary proceedings, voting records, MEP data",
    price: 449.99,
    category: "Government",
    format: "JSON",
    records: 280000,
    preview: databasePreview,
    tags: ["government", "france", "strasbourg"],
    lastUpdated: "2024-01-20",
    source: "European Parliament",
    schema: "session_id, topic, vote_results, mep_attendance, date"
  },
  {
    id: "95",
    name: "Bordeaux Wine Trade Database - France",
    description: "Wine auctions, pricing, vintage data, exports",
    price: 599.99,
    category: "Agriculture",
    format: "CSV",
    records: 680000,
    preview: databasePreview,
    tags: ["wine", "france", "bordeaux"],
    lastUpdated: "2024-01-19",
    source: "Bordeaux Wine Council",
    schema: "chateau_name, vintage, price_eur, production, ratings"
  },
  {
    id: "96",
    name: "Lille Retail Database - France",
    description: "Shopping centers, retail sales, consumer data",
    price: 349.99,
    category: "Retail",
    format: "XLSX",
    records: 420000,
    preview: databasePreview,
    tags: ["retail", "france", "lille"],
    lastUpdated: "2024-01-18",
    source: "French Retail Association",
    schema: "store_id, category, sales_eur, customer_count, location"
  },
  {
    id: "97",
    name: "Darwin Tourism Database - Australia",
    description: "Northern Territory attractions, Aboriginal tourism",
    price: 299.99,
    category: "Tourism",
    format: "JSON",
    records: 280000,
    preview: databasePreview,
    tags: ["tourism", "australia", "darwin"],
    lastUpdated: "2024-01-17",
    source: "Tourism Northern Territory",
    schema: "visitor_id, attractions, spending, origin, activities"
  },
  {
    id: "98",
    name: "Wollongong Industrial Database - Australia",
    description: "Steel manufacturing, mining, industrial operations",
    price: 449.99,
    category: "Manufacturing",
    format: "CSV",
    records: 8500,
    preview: databasePreview,
    tags: ["manufacturing", "australia", "wollongong"],
    lastUpdated: "2024-01-16",
    source: "NSW Industry Association",
    schema: "company_name, industry, production_volume, employees, exports"
  },
  {
    id: "99",
    name: "Newcastle Mining Database - Australia",
    description: "Coal exports, port operations, mining employment",
    price: 549.99,
    category: "Mining",
    format: "XLSX",
    records: 45000,
    preview: databasePreview,
    tags: ["mining", "australia", "newcastle"],
    lastUpdated: "2024-01-15",
    source: "NSW Mining Council",
    schema: "mine_name, production_volume, exports, employees, reserves"
  },
  {
    id: "100",
    name: "Portland Tech Startups Database - USA",
    description: "Startup ecosystem, funding rounds, company data",
    price: 399.99,
    category: "Technology",
    format: "JSON",
    records: 4500,
    preview: databasePreview,
    tags: ["startups", "usa", "portland"],
    lastUpdated: "2024-01-20",
    source: "Portland Tech Alliance",
    schema: "company_name, founding_date, funding, employees, products"
  },
  {
    id: "101",
    name: "Denver Cannabis Industry Database - USA",
    description: "Dispensaries, cultivation, sales data, regulations",
    price: 499.99,
    category: "Agriculture",
    format: "CSV",
    records: 12000,
    preview: databasePreview,
    tags: ["cannabis", "usa", "denver"],
    lastUpdated: "2024-01-19",
    source: "Colorado Cannabis Association",
    schema: "business_id, license_type, sales, location, compliance"
  },
  {
    id: "102",
    name: "Phoenix Real Estate Database - USA",
    description: "Property listings, market trends, development projects",
    price: 449.99,
    category: "Real Estate",
    format: "XLSX",
    records: 680000,
    preview: databasePreview,
    tags: ["property", "usa", "phoenix"],
    lastUpdated: "2024-01-18",
    source: "Arizona Regional MLS",
    schema: "listing_id, address, price, bedrooms, square_feet, date"
  },
  {
    id: "103",
    name: "Liverpool Football Industry Database - UK",
    description: "Football clubs, player data, match statistics",
    price: 349.99,
    category: "Sports",
    format: "JSON",
    records: 280000,
    preview: databasePreview,
    tags: ["sports", "uk", "liverpool"],
    lastUpdated: "2024-01-17",
    source: "English Football League",
    schema: "player_id, club, position, stats, value, transfer_history"
  },
  {
    id: "104",
    name: "Newcastle University Research Database - UK",
    description: "Research projects, publications, funding data",
    price: 299.99,
    category: "Education",
    format: "CSV",
    records: 45000,
    preview: databasePreview,
    tags: ["education", "uk", "newcastle"],
    lastUpdated: "2024-01-16",
    source: "Newcastle University",
    schema: "project_id, researcher, funding, publications, field"
  },
  {
    id: "105",
    name: "Belfast Tech Industry Database - UK",
    description: "Software development, cybersecurity, tech employment",
    price: 399.99,
    category: "Technology",
    format: "XLSX",
    records: 8500,
    preview: databasePreview,
    tags: ["technology", "uk", "belfast"],
    lastUpdated: "2024-01-15",
    source: "Northern Ireland Tech",
    schema: "company_name, products, employees, revenue, growth"
  },
  {
    id: "106",
    name: "Regina Agriculture Database - Canada",
    description: "Grain farming, canola production, livestock",
    price: 349.99,
    category: "Agriculture",
    format: "JSON",
    records: 28000,
    preview: databasePreview,
    tags: ["agriculture", "canada", "regina"],
    lastUpdated: "2024-01-20",
    source: "Saskatchewan Agriculture",
    schema: "farm_id, crop_type, yield, livestock_count, farm_size"
  },
  {
    id: "107",
    name: "Saskatoon Potash Mining Database - Canada",
    description: "Potash production, mining operations, exports",
    price: 549.99,
    category: "Mining",
    format: "CSV",
    records: 8500,
    preview: databasePreview,
    tags: ["mining", "canada", "saskatoon"],
    lastUpdated: "2024-01-19",
    source: "Saskatchewan Mining Association",
    schema: "mine_name, production_volume, reserves, employees, exports"
  },
  {
    id: "108",
    name: "Victoria BC Tourism Database - Canada",
    description: "Tourism attractions, hotel data, cruise ships",
    price: 329.99,
    category: "Tourism",
    format: "XLSX",
    records: 420000,
    preview: databasePreview,
    tags: ["tourism", "canada", "victoria"],
    lastUpdated: "2024-01-18",
    source: "Tourism Victoria",
    schema: "visitor_id, origin, attractions, spending, accommodation"
  },
  {
    id: "109",
    name: "Napier Wine Database - NZ",
    description: "Hawke's Bay wineries, production, wine tourism",
    price: 299.99,
    category: "Agriculture",
    format: "JSON",
    records: 4500,
    preview: databasePreview,
    tags: ["wine", "new-zealand", "napier"],
    lastUpdated: "2024-01-17",
    source: "Hawke's Bay Wine Association",
    schema: "winery_name, production_volume, varieties, visitor_count"
  },
  {
    id: "110",
    name: "Palmerston North Agriculture Database - NZ",
    description: "Dairy farming, sheep farming, agricultural research",
    price: 349.99,
    category: "Agriculture",
    format: "CSV",
    records: 48000,
    preview: databasePreview,
    tags: ["agriculture", "new-zealand", "palmerston-north"],
    lastUpdated: "2024-01-16",
    source: "Massey University Research",
    schema: "farm_id, farm_type, livestock_count, production_volume, research_projects"
  },
  {
    id: "111",
    name: "Invercargill Fishing Industry Database - NZ",
    description: "Commercial fishing, seafood exports, aquaculture",
    price: 299.99,
    category: "Maritime",
    format: "XLSX",
    records: 8500,
    preview: databasePreview,
    tags: ["fishing", "new-zealand", "invercargill"],
    lastUpdated: "2024-01-15",
    source: "NZ Seafood Industry Council",
    schema: "vessel_id, catch_type, catch_volume, fishing_grounds, export_markets"
  },
  {
    id: "112",
    name: "Aberdeen Oil & Gas Database - UK",
    description: "North Sea oil rigs, production data, employment",
    price: 749.99,
    category: "Energy",
    format: "JSON",
    records: 45000,
    preview: databasePreview,
    tags: ["energy", "uk", "aberdeen"],
    lastUpdated: "2024-01-20",
    source: "Oil & Gas UK",
    schema: "field_name, operator, production_volume, reserves, platform_type"
  },
  {
    id: "113",
    name: "Oxford University Research Database - UK",
    description: "Academic research, publications, patents, funding",
    price: 649.99,
    category: "Education",
    format: "CSV",
    records: 280000,
    preview: databasePreview,
    tags: ["education", "uk", "oxford"],
    lastUpdated: "2024-01-19",
    source: "Oxford University",
    schema: "researcher_id, department, publications, citations, grants"
  },
  {
    id: "114",
    name: "Cambridge Tech Cluster Database - UK",
    description: "Technology startups, biotech, VC funding",
    price: 549.99,
    category: "Technology",
    format: "XLSX",
    records: 4500,
    preview: databasePreview,
    tags: ["technology", "uk", "cambridge"],
    lastUpdated: "2024-01-18",
    source: "Cambridge Network",
    schema: "company_name, sector, funding_rounds, employees, patents"
  },
  {
    id: "115",
    name: "Edmonton Healthcare Database - Canada",
    description: "Hospital networks, patient volumes, medical research",
    price: 499.99,
    category: "Healthcare",
    format: "JSON",
    records: 1200000,
    preview: databasePreview,
    tags: ["healthcare", "canada", "edmonton"],
    lastUpdated: "2024-01-17",
    source: "Alberta Health Services",
    schema: "facility_id, patient_count, treatments, research_projects"
  },
  {
    id: "116",
    name: "Kelowna Wine Industry Database - Canada",
    description: "Okanagan wineries, production, wine tourism",
    price: 329.99,
    category: "Agriculture",
    format: "CSV",
    records: 2800,
    preview: databasePreview,
    tags: ["wine", "canada", "kelowna"],
    lastUpdated: "2024-01-16",
    source: "BC Wine Institute",
    schema: "winery_name, production_volume, varieties, visitor_count, awards"
  },
  {
    id: "117",
    name: "Thunder Bay Port Operations - Canada",
    description: "Great Lakes shipping, grain exports, cargo volumes",
    price: 399.99,
    category: "Logistics",
    format: "XLSX",
    records: 120000,
    preview: databasePreview,
    tags: ["logistics", "canada", "thunder-bay"],
    lastUpdated: "2024-01-15",
    source: "Thunder Bay Port Authority",
    schema: "shipment_id, cargo_type, tonnage, destination, date"
  },
  {
    id: "118",
    name: "Guangzhou Manufacturing Database - HK Region",
    description: "Factory production, exports, supply chain data",
    price: 599.99,
    category: "Manufacturing",
    format: "JSON",
    records: 680000,
    preview: databasePreview,
    tags: ["manufacturing", "hong-kong", "guangzhou"],
    lastUpdated: "2024-01-20",
    source: "Guangdong Manufacturing Association",
    schema: "factory_id, products, production_volume, employees, exports"
  },
  {
    id: "119",
    name: "Hong Kong Aviation Database",
    description: "Airport operations, flight data, passenger statistics",
    price: 549.99,
    category: "Transportation",
    format: "CSV",
    records: 4500000,
    preview: databasePreview,
    tags: ["aviation", "hong-kong", "transportation"],
    lastUpdated: "2024-01-19",
    source: "Hong Kong International Airport",
    schema: "flight_id, airline, route, passengers, cargo_weight, date"
  },
  {
    id: "120",
    name: "Lantau Island Tourism Database - HK",
    description: "Theme parks, tourist attractions, visitor data",
    price: 399.99,
    category: "Tourism",
    format: "XLSX",
    records: 2800000,
    preview: databasePreview,
    tags: ["tourism", "hong-kong", "lantau"],
    lastUpdated: "2024-01-18",
    source: "HK Tourism Board",
    schema: "visitor_id, attractions, spending, origin, satisfaction"
  },
  {
    id: "121",
    name: "Fortaleza Tourism Database - Brazil",
    description: "Beach tourism, hotels, visitor demographics",
    price: 329.99,
    category: "Tourism",
    format: "JSON",
    records: 620000,
    preview: databasePreview,
    tags: ["tourism", "brazil", "fortaleza"],
    lastUpdated: "2024-01-17",
    source: "Ceará Tourism Board",
    schema: "visitor_id, origin, accommodation, spending, activities"
  },
  {
    id: "122",
    name: "Porto Alegre Tech Industry - Brazil",
    description: "Software development, IT services, tech startups",
    price: 449.99,
    category: "Technology",
    format: "CSV",
    records: 8500,
    preview: databasePreview,
    tags: ["technology", "brazil", "porto-alegre"],
    lastUpdated: "2024-01-16",
    source: "Brazilian Tech Association",
    schema: "company_name, products, employees, revenue, funding"
  },
  {
    id: "123",
    name: "Belo Horizonte Mining Database - Brazil",
    description: "Iron ore mining, production, employment data",
    price: 699.99,
    category: "Mining",
    format: "XLSX",
    records: 28000,
    preview: databasePreview,
    tags: ["mining", "brazil", "belo-horizonte"],
    lastUpdated: "2024-01-15",
    source: "Brazilian Mining Institute",
    schema: "mine_id, ore_type, production_volume, reserves, employees"
  },
  {
    id: "124",
    name: "Tucumán Agriculture Database - Argentina",
    description: "Sugar cane, citrus production, agricultural data",
    price: 329.99,
    category: "Agriculture",
    format: "JSON",
    records: 18000,
    preview: databasePreview,
    tags: ["agriculture", "argentina", "tucuman"],
    lastUpdated: "2024-01-20",
    source: "Tucumán Agriculture Ministry",
    schema: "farm_id, crop_type, yield, area_hectares, harvest_date"
  },
  {
    id: "125",
    name: "Salta Tourism Database - Argentina",
    description: "Wine routes, mountain tourism, visitor statistics",
    price: 299.99,
    category: "Tourism",
    format: "CSV",
    records: 280000,
    preview: databasePreview,
    tags: ["tourism", "argentina", "salta"],
    lastUpdated: "2024-01-19",
    source: "Salta Tourism Board",
    schema: "visitor_id, attractions, spending, origin, season"
  },
  {
    id: "126",
    name: "Ushuaia Tourism Database - Argentina",
    description: "Antarctica cruises, winter sports, southernmost tourism",
    price: 349.99,
    category: "Tourism",
    format: "XLSX",
    records: 180000,
    preview: databasePreview,
    tags: ["tourism", "argentina", "ushuaia"],
    lastUpdated: "2024-01-18",
    source: "Tierra del Fuego Tourism",
    schema: "visitor_id, activities, cruise_bookings, spending, season"
  },
  {
    id: "127",
    name: "Nuremberg Manufacturing Database - Germany",
    description: "Industrial machinery, electronics, production data",
    price: 549.99,
    category: "Manufacturing",
    format: "JSON",
    records: 48000,
    preview: databasePreview,
    tags: ["manufacturing", "germany", "nuremberg"],
    lastUpdated: "2024-01-17",
    source: "Bavarian Manufacturing Association",
    schema: "company_name, products, production_volume, employees, exports"
  },
  {
    id: "128",
    name: "Leipzig Trade Fair Database - Germany",
    description: "Exhibition data, trade shows, business events",
    price: 399.99,
    category: "Business",
    format: "CSV",
    records: 120000,
    preview: databasePreview,
    tags: ["business", "germany", "leipzig"],
    lastUpdated: "2024-01-16",
    source: "Leipzig Messe",
    schema: "event_id, exhibitors, visitors, industry, date, revenue"
  },
  {
    id: "129",
    name: "Hannover Industrial Database - Germany",
    description: "Industrial manufacturing, trade fair data, innovation",
    price: 499.99,
    category: "Manufacturing",
    format: "XLSX",
    records: 85000,
    preview: databasePreview,
    tags: ["manufacturing", "germany", "hannover"],
    lastUpdated: "2024-01-15",
    source: "Hannover Messe",
    schema: "company_name, industry, products, innovation_index, employees"
  },
  {
    id: "130",
    name: "Nantes Maritime Database - France",
    description: "Shipbuilding, port operations, maritime industry",
    price: 449.99,
    category: "Maritime",
    format: "JSON",
    records: 48000,
    preview: databasePreview,
    tags: ["maritime", "france", "nantes"],
    lastUpdated: "2024-01-20",
    source: "French Maritime Industry",
    schema: "company_name, projects, employees, contracts, vessel_types"
  },
  {
    id: "131",
    name: "Montpellier Tech Hub Database - France",
    description: "Tech startups, innovation centers, VC funding",
    price: 399.99,
    category: "Technology",
    format: "CSV",
    records: 4500,
    preview: databasePreview,
    tags: ["technology", "france", "montpellier"],
    lastUpdated: "2024-01-19",
    source: "French Tech Montpellier",
    schema: "company_name, sector, funding, employees, products"
  },
  {
    id: "132",
    name: "Cannes Film Industry Database - France",
    description: "Production companies, film festivals, industry data",
    price: 549.99,
    category: "Media",
    format: "XLSX",
    records: 28000,
    preview: databasePreview,
    tags: ["media", "france", "cannes"],
    lastUpdated: "2024-01-18",
    source: "French Film Commission",
    schema: "company_name, productions, budget, employees, awards"
  },
  {
    id: "133",
    name: "Austin Music Industry Database - USA",
    description: "Music venues, festivals, artist data, industry revenue",
    price: 399.99,
    category: "Entertainment",
    format: "JSON",
    records: 45000,
    preview: databasePreview,
    tags: ["entertainment", "usa", "austin"],
    lastUpdated: "2024-01-17",
    source: "Austin Music Foundation",
    schema: "venue_name, capacity, events, artists, revenue"
  },
  {
    id: "134",
    name: "Nashville Healthcare Database - USA",
    description: "Hospital systems, health insurance, medical billing",
    price: 649.99,
    category: "Healthcare",
    format: "CSV",
    records: 2800000,
    preview: databasePreview,
    tags: ["healthcare", "usa", "nashville"],
    lastUpdated: "2024-01-16",
    source: "Tennessee Health Department",
    schema: "claim_id, provider, service_type, cost, insurance, date"
  },
  {
    id: "135",
    name: "Detroit Automotive Revival Database - USA",
    description: "Auto manufacturing, EV production, industry employment",
    price: 599.99,
    category: "Automotive",
    format: "XLSX",
    records: 180000,
    preview: databasePreview,
    tags: ["automotive", "usa", "detroit"],
    lastUpdated: "2024-01-15",
    source: "Michigan Automotive Partnership",
    schema: "company_name, production_volume, ev_models, employees, plants"
  },
  {
    id: "136",
    name: "Nottingham Pharmaceutical Database - UK",
    description: "Pharma companies, drug development, clinical trials",
    price: 699.99,
    category: "Healthcare",
    format: "JSON",
    records: 85000,
    preview: databasePreview,
    tags: ["pharmaceutical", "uk", "nottingham"],
    lastUpdated: "2024-01-20",
    source: "UK Pharmaceutical Association",
    schema: "company_name, drugs_in_development, trials, employees, revenue"
  },
  {
    id: "137",
    name: "Sheffield Manufacturing Database - UK",
    description: "Steel production, advanced manufacturing, employment",
    price: 449.99,
    category: "Manufacturing",
    format: "CSV",
    records: 28000,
    preview: databasePreview,
    tags: ["manufacturing", "uk", "sheffield"],
    lastUpdated: "2024-01-19",
    source: "Sheffield Manufacturing Forum",
    schema: "company_name, products, production_volume, employees, exports"
  },
  {
    id: "138",
    name: "Plymouth Marine Science Database - UK",
    description: "Oceanographic research, marine biology, naval data",
    price: 549.99,
    category: "Research",
    format: "XLSX",
    records: 120000,
    preview: databasePreview,
    tags: ["research", "uk", "plymouth"],
    lastUpdated: "2024-01-18",
    source: "Plymouth Marine Laboratory",
    schema: "project_id, research_area, funding, publications, collaborators"
  },
  {
    id: "139",
    name: "St. John's Offshore Oil Database - Canada",
    description: "Atlantic oil fields, production, employment data",
    price: 749.99,
    category: "Energy",
    format: "JSON",
    records: 28000,
    preview: databasePreview,
    tags: ["energy", "canada", "st-johns"],
    lastUpdated: "2024-01-17",
    source: "Newfoundland Offshore Petroleum Board",
    schema: "field_name, operator, production_volume, reserves, platform_type"
  },
  {
    id: "140",
    name: "Charlottetown Tourism Database - Canada",
    description: "PEI tourism, Anne of Green Gables, visitor data",
    price: 279.99,
    category: "Tourism",
    format: "CSV",
    records: 280000,
    preview: databasePreview,
    tags: ["tourism", "canada", "charlottetown"],
    lastUpdated: "2024-01-16",
    source: "Tourism PEI",
    schema: "visitor_id, origin, attractions, spending, accommodation"
  },
  {
    id: "141",
    name: "Whitehorse Mining Database - Canada",
    description: "Yukon mining operations, gold production, mineral exploration",
    price: 549.99,
    category: "Mining",
    format: "XLSX",
    records: 4500,
    preview: databasePreview,
    tags: ["mining", "canada", "whitehorse"],
    lastUpdated: "2024-01-15",
    source: "Yukon Mining Association",
    schema: "mine_name, mineral_type, production_volume, reserves, employees"
  },
  {
    id: "142",
    name: "New Plymouth Energy Database - NZ",
    description: "Oil and gas operations, Taranaki region energy data",
    price: 449.99,
    category: "Energy",
    format: "JSON",
    records: 12000,
    preview: databasePreview,
    tags: ["energy", "new-zealand", "new-plymouth"],
    lastUpdated: "2024-01-20",
    source: "NZ Petroleum & Minerals",
    schema: "field_name, operator, production_volume, reserves, extraction_method"
  },
  {
    id: "143",
    name: "Gisborne Wine & Agriculture - NZ",
    description: "Chardonnay production, viticulture, agricultural data",
    price: 299.99,
    category: "Agriculture",
    format: "CSV",
    records: 4500,
    preview: databasePreview,
    tags: ["agriculture", "new-zealand", "gisborne"],
    lastUpdated: "2024-01-19",
    source: "Gisborne Wine Association",
    schema: "vineyard_name, production_volume, varieties, export_data"
  },
  {
    id: "144",
    name: "Whangarei Marine Industry - NZ",
    description: "Boat building, fishing industry, marina operations",
    price: 329.99,
    category: "Maritime",
    format: "XLSX",
    records: 8500,
    preview: databasePreview,
    tags: ["maritime", "new-zealand", "whangarei"],
    lastUpdated: "2024-01-18",
    source: "Northland Marine Industry",
    schema: "company_name, industry_type, employees, revenue, projects"
  },
  {
    id: "145",
    name: "Tsuen Wan Industrial Database - HK",
    description: "Manufacturing facilities, industrial estates, production",
    price: 449.99,
    category: "Manufacturing",
    format: "JSON",
    records: 48000,
    preview: databasePreview,
    tags: ["manufacturing", "hong-kong", "tsuen-wan"],
    lastUpdated: "2024-01-17",
    source: "HK Industrial Estates Corporation",
    schema: "company_name, products, production_volume, employees, exports"
  },
  {
    id: "146",
    name: "Sha Tin Retail Database - HK",
    description: "Shopping malls, retail sales, consumer behavior",
    price: 399.99,
    category: "Retail",
    format: "CSV",
    records: 1200000,
    preview: databasePreview,
    tags: ["retail", "hong-kong", "sha-tin"],
    lastUpdated: "2024-01-16",
    source: "HK Retail Management Association",
    schema: "store_id, mall, sales, customer_count, category"
  },
  {
    id: "147",
    name: "Tung Chung Logistics Database - HK",
    description: "Airport logistics, cargo handling, warehousing",
    price: 549.99,
    category: "Logistics",
    format: "XLSX",
    records: 680000,
    preview: databasePreview,
    tags: ["logistics", "hong-kong", "tung-chung"],
    lastUpdated: "2024-01-15",
    source: "HK Logistics Association",
    schema: "shipment_id, cargo_type, weight, destination, handling_time"
  },
  {
    id: "148",
    name: "Florianópolis Tech Hub - Brazil",
    description: "Software development, tech startups, innovation data",
    price: 399.99,
    category: "Technology",
    format: "JSON",
    records: 4500,
    preview: databasePreview,
    tags: ["technology", "brazil", "florianopolis"],
    lastUpdated: "2024-01-20",
    source: "Santa Catarina Tech Association",
    schema: "company_name, products, funding, employees, growth_rate"
  },
  {
    id: "149",
    name: "Goiânia Agriculture Database - Brazil",
    description: "Soybean production, cattle ranching, agribusiness",
    price: 449.99,
    category: "Agriculture",
    format: "CSV",
    records: 280000,
    preview: databasePreview,
    tags: ["agriculture", "brazil", "goiania"],
    lastUpdated: "2024-01-19",
    source: "Goiás Agriculture Federation",
    schema: "farm_id, crop_type, yield, livestock_count, area_hectares"
  },
  {
    id: "150",
    name: "Campinas Industrial Database - Brazil",
    description: "Manufacturing, technology parks, R&D centers",
    price: 549.99,
    category: "Manufacturing",
    format: "XLSX",
    records: 85000,
    preview: databasePreview,
    tags: ["manufacturing", "brazil", "campinas"],
    lastUpdated: "2024-01-18",
    source: "Campinas Industrial Association",
    schema: "company_name, industry, production_volume, employees, innovation"
  },
  {
    id: "151",
    name: "Neuquén Oil & Gas Database - Argentina",
    description: "Vaca Muerta shale, fracking operations, energy production",
    price: 699.99,
    category: "Energy",
    format: "JSON",
    records: 28000,
    preview: databasePreview,
    tags: ["energy", "argentina", "neuquen"],
    lastUpdated: "2024-01-17",
    source: "Argentine Energy Secretary",
    schema: "field_name, operator, production_volume, reserves, extraction_method"
  },
  {
    id: "152",
    name: "San Miguel de Tucumán Business - Argentina",
    description: "SME business directory, industry classification",
    price: 249.99,
    category: "Business",
    format: "CSV",
    records: 48000,
    preview: databasePreview,
    tags: ["business", "argentina", "tucuman"],
    lastUpdated: "2024-01-16",
    source: "Tucumán Business Chamber",
    schema: "business_id, name, industry, employees, revenue_bracket"
  },
  {
    id: "153",
    name: "Santa Fe Agriculture Database - Argentina",
    description: "Soy and wheat production, agricultural exports",
    price: 449.99,
    category: "Agriculture",
    format: "XLSX",
    records: 180000,
    preview: databasePreview,
    tags: ["agriculture", "argentina", "santa-fe"],
    lastUpdated: "2024-01-15",
    source: "Santa Fe Agriculture Ministry",
    schema: "farm_id, crop_type, yield, area_hectares, export_volume"
  },
  {
    id: "154",
    name: "Bonn Government Database - Germany",
    description: "Federal agencies, civil service, government operations",
    price: 499.99,
    category: "Government",
    format: "JSON",
    records: 85000,
    preview: databasePreview,
    tags: ["government", "germany", "bonn"],
    lastUpdated: "2024-01-20",
    source: "German Federal Government",
    schema: "agency_name, department, employees, budget, location"
  },
  {
    id: "155",
    name: "Essen Industrial Heritage Database - Germany",
    description: "Coal mining history, industrial tourism, heritage sites",
    price: 349.99,
    category: "Tourism",
    format: "CSV",
    records: 12000,
    preview: databasePreview,
    tags: ["tourism", "germany", "essen"],
    lastUpdated: "2024-01-19",
    source: "Ruhr Tourism Association",
    schema: "site_name, visitor_count, historical_data, preservation_status"
  },
  {
    id: "156",
    name: "Bremen Logistics Database - Germany",
    description: "Port operations, automotive logistics, cargo handling",
    price: 549.99,
    category: "Logistics",
    format: "XLSX",
    records: 480000,
    preview: databasePreview,
    tags: ["logistics", "germany", "bremen"],
    lastUpdated: "2024-01-18",
    source: "Bremen Port Authority",
    schema: "shipment_id, cargo_type, vehicle_count, destination, date"
  }
];

const Index = () => {
  const [products, setProducts] = useState<Product[]>(sampleProducts);
  const [cartItems, setCartItems] = useState<CartItem[]>([]);
  const [showUploader, setShowUploader] = useState(false);
  const [showCart, setShowCart] = useState(false);

  const handleAddToCart = (product: Product) => {
    setCartItems(prev => {
      const existingItem = prev.find(item => item.id === product.id);
      if (existingItem) {
        return prev.map(item =>
          item.id === product.id
            ? { ...item, quantity: item.quantity + 1 }
            : item
        );
      }
      return [...prev, { ...product, quantity: 1 }];
    });
  };

  const handleRemoveFromCart = (productId: string) => {
    setCartItems(prev => prev.filter(item => item.id !== productId));
  };

  const handleUpdateQuantity = (productId: string, quantity: number) => {
    setCartItems(prev =>
      prev.map(item =>
        item.id === productId ? { ...item, quantity } : item
      )
    );
  };

  const handleProductsAdded = (newProducts: Product[]) => {
    setProducts(prev => [...prev, ...newProducts]);
  };

  const cartCount = cartItems.reduce((sum, item) => sum + item.quantity, 0);

  return (
    <div className="min-h-screen bg-background">
      <ShopHeader
        cartCount={cartCount}
        onCartClick={() => setShowCart(true)}
        onUploadClick={() => setShowUploader(true)}
      />

      <main className="container mx-auto px-4 py-8">
        <div className="mb-8">
          <h2 className="text-3xl font-bold text-foreground mb-2">
            Premium Database Marketplace
          </h2>
          <p className="text-muted-foreground text-lg">
            High-quality, verified databases for your business needs. Pay securely with Bitcoin and receive instant delivery.
          </p>
        </div>

        <ProductTable
          products={products}
          onAddToCart={handleAddToCart}
        />
      </main>

      {/* Upload Dialog */}
      <Dialog open={showUploader} onOpenChange={setShowUploader}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <FileUploader
            onProductsAdded={handleProductsAdded}
            onClose={() => setShowUploader(false)}
          />
        </DialogContent>
      </Dialog>

      {/* Cart Dialog */}
      <Dialog open={showCart} onOpenChange={setShowCart}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <Cart
            items={cartItems}
            onClose={() => setShowCart(false)}
            onRemoveItem={handleRemoveFromCart}
            onUpdateQuantity={handleUpdateQuantity}
          />
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default Index;
